---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

# TODO: Remove this when and if that becomes possible.  See
# cisagov/skeleton-packer#301.
- name: >-
    Import playbook to install prerequisites for the Netplan
    configuration fix
  ansible.builtin.import_playbook: install-prerequisites-for-netplan-configuration-fix.yml

- name: Import playbook to fix a minor issue with the OpenSSH installation
  ansible.builtin.import_playbook: fix-openssh.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import hardening playbook
  ansible.builtin.import_playbook: harden.yml

- name: Import Wazuh agent playbook
  ansible.builtin.import_playbook: wazuh_agent.yml
